analytics: {}
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.456081
  lightness: 0.650338
  rhythmicContrast: 0.402027
  saturation: 0.808277
cta: {}
layout_spectrum: 0.482264
name: yulizar
opengraph: {}
purpose: []
typography_spectrum: 0.2998818946070969
