name: yulizar
favicon: null
layout_spectrum: 0.38670985610224307
typography_spectrum: 0.2998818946070969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9604895634111017
  lightness: 0.532136446563527
  saturation: 0.6584692047908902
  rhythmicContrast: 0.22571216826327145
purpose: []
